description: pointnext
target:
  service: sing
  name: msroctovc

environment:
  image: jamekuma/pointnext_cls:latest
  
storage:
  output:
    storage_account_name: igsharestorage
    container_name: v-jixiong
    mount_dir: /mnt/output
  input:
    storage_account_name: igsharestorage
    container_name: v-jixiong
    mount_dir: /mnt/input
code:
  local_dir: .


jobs:

- name: 0228_pointnext_enhancesurf
  sku: G1
  preemptible: False
  priority: High
  # azml_int: True
  command:
  - bash my_scripts/0228_pointnext_enhancesurf.sh